<input type="hidden" name="<?= $block->escapeHtmlAttr($this->getNamePrefix()) ?>" value="" /><!-- this is send if nothing is checked -->
<label class="switch">
    <?php foreach ($this->getValues() as $name => $label): ?>
        <input type="checkbox" value="<?= $block->escapeHtmlAttr($name); ?>"
               name="<?= $block->escapeHtmlAttr($this->getNamePrefix()) ?>[]"
               id="<?= $block->escapeHtmlAttr($this->getHtmlId()) ?>"
            <?= ($this->isChecked() ? ' checked="checked"' : '') ?>
        />
        <div class="slider round"></div>
    <?php endforeach;?>
</label>
